FROM debian:bookwork

RUN apt-get update && apt-get install -y \
  wget \
  git \
  lsb-release \
  software-properties-common \
  gnupg \
  curl \
  build-essential \
  devscripts \
  debhelper \
  pkg-config \
  zstd \
  libclang-dev \
  libudev-dev \
  libiio-dev \
  squashfs-tools && \
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
